### ISSUE TITLE
defork this repo

### ISSUE THREAD

**Issue by MoralCode** [RITlug/wiki#3]
since we're planning on making major changes, it probably doesnt make sense for this do be discoverable as a fork of my repo which is istelf a fork of a UNICEF wiki repo. 

I think github support or the chatbot has the ability to do this per this article: https://github.community/t/de-forking-a-github-repo/537

**Comment by zethra** [comment]
I submitted a support ticket for it.

**Comment by MoralCode** [comment]
awesome, thanks!

**Comment by MoralCode** [comment]
looks like it went through!
