### ISSUE TITLE
Link for CS users currently 404s

### ISSUE THREAD

**Issue by blizzardfinnegan** [RITlug/wiki#6]
Steps to reproduce: 
1. Open `wiki.ritlug.com`
2. Click `Using linux at RIT for CS majors`
3. 404 error displays

Alternative steps:
1. Open `wiki.ritlug.com/cs`
2. 404 error displays

**Comment by MoralCode** [comment]
fixed in ae9495707db5bd41555c69f17425afa542c548bb. thanks!
